### ISSUE TITLE
request: confine plugin to admin area

### ISSUE THREAD

**Issue by cspicuzza** [helgatheviking/Radio-Buttons-for-Taxonomies#35]
This plugin is great, thank you!   I noticed it was running a query on the front end of themes.  Is this necessary?  Can you add a conditional statement (is_admin) to keep all queries in the admin area?

**Comment by helgatheviking** [comment]
What query are you referring to?

**Comment by cspicuzza** [comment]
I added this and it worked for me:

https://gist.github.com/cspicuzza/2a4ddbf73027f3867b58

**Comment by helgatheviking** [comment]
What problem are you seeing? Though I guess it is true that the whole thing runs in the admin.

**Comment by cspicuzza** [comment]
It's not so much a problem.  I just noticed it was fetching options for this plugin on the front end of the site which is probably not necessary.  Either way, no biggie!

**Comment by helgatheviking** [comment]
Ok cool. I think at one point it was filtering `get_terms()` everywhere, but now I think you're right that it only functions on the admin side. 

However, your gist doesn't actually prevent the `get_option()` from running on the front-end. That's firing when the plugin is loaded and then is used on `registered_taxonomy` (which runs on `init` since that it where taxonomies are registered). And on `init` you don't know if you are in the admin or not. 

If I skipped the `registered_taxonomy` hook, I could probably do something with either `get_taxonomies()` or access the taxonomy global variable. Either way, I think it might be more effort than it is worth.
