### ISSUE TITLE
Doens´t work on multisite

### ISSUE THREAD

**Issue by rborgiel** [helgatheviking/Radio-Buttons-for-Taxonomies#36]
Hi Kathy,
great plugin you did, but i have one question.
When i uncomment these lines of my code it works on multisite´s.

```
// prevent weirdness with multisite
       if( function_exists( 'ms_is_switched' ) && ms_is_switched() )
       return $post_id;
```

Can you explain these lines? is it necessary?

**Comment by helgatheviking** [comment]
Looks like I used the same extremely descriptive words as the [commit message[(https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/commit/73e1c001f82636b35f690fa1b721cf162a7fae2b). And since that was a year ago, so I have little idea what that code is meant to be doing. Based on what `ms_is_switched()` does I'd guess it was meant to only save the terms on the current site and not randomly on any others. 

Are you saying that with these lines in place you cannot save terms on a sub site?

**Comment by helgatheviking** [comment]
I'm able to save single terms on each sub-site, so closing. Looks like the `ms_is_switched()` was added by the developers from Multilingual Press as related to https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/issues/23
