### ISSUE TITLE
Remove meta boxes called many times on all admin pages

### ISSUE THREAD

**Issue by remcokalf** [helgatheviking/Radio-Buttons-for-Taxonomies#93]
Hi Helga, 

I was looking for ways to speed up Admin performance and came across an issue that also plays in this plugin. 

The remove_meta_box function, this one:

class.WordPress_Radio_Taxonomy.php 
add_action in line 46
function remove_meta_box in line 76

This function is being called many times on all admin pages, where it is only needed on post type edit screens where there is a radio metabox, and only once for each radio taxonomy that post type is connected to.

In my case my taxonomies that are set to have radio buttons are connected to multiple post types. 
The remove_meta_box function is called for every posttype it is connected to, for each of these taxonomies, on every pages. This adds up quickly:

Specifically in my case I have 4 radio taxonomies. Each is connected to 4 custom post types. This results in 16 calls to remove_meta_box, where only one or two are needed. And even worse, these 16 calls happen on ALL admin pages, also on post types that have no radio buttons, and literally every admin page like Plugins, Media etc.

I use something like below to prevent this, in other scenario's where I know the post type in advance. I check for get_current_screen(), and let it only run if it is needed, checking if it is present in an array of posttypes. Would have to be adapted of course.

Also, more or less the same happens for add_meta_box function. 

I am hoping you are able to fix this. Thanks!

```
function remove_unwanted_metaboxes( ) {

	// The admin pages that don't have get_current_screen  won't have metaboxes 
	if ( function_exists( 'get_current_screen' ) ) {
		
		$postType = get_current_screen()->post_type;

		$postTypes = array(
			'page',
			'post'
		); //this should be dynamic of course

		if ( in_array( $postType, $postTypes ) ) {

			remove_meta_box( 'mymetaboxid', $postType, 'side' );

		}
	}
}
add_action( 'admin_head', 'remove_unwanted_metaboxes' );
```

**Comment by helgatheviking** [comment]
Hi, thanks for the report. Are the extra calls resulting in a significant performance issue? 

I suspect this is related to how the plugin was originally (and currently) structured to create an instance of `WordPress_Radio_Taxonomy` for each taxonomy that is converted to radios. And then add the hooks/filters each time. It's kind one of those things you look back and wince at old code. 

I [opened an issue to consider re-factoring ](https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/issues/66)this so that all the hooks are only added once and the "is this a radio taxonomy" condition is done inside each method.

I must admit this project is not top priority for me though so not sure when I might be able to do that.  I am, however, very open to Pull Requests, if this was something you wanted to help with.

**Comment by remcokalf** [comment]
I don't know how much it exactly hurts performance, but as always things add up in an already very slow admin, in a complex site I am working on that has a lot of custom post types with a lot of metaboxes, which are rearranged with another plugin Tabify Edit Screen. So this is just one of those things running unnecessary and way too many times. I stumbled upon it when removing metaboxes myself, and noticing some calls were running 20 times or more.

I understand time concern and priorities, any improvement in the future is appreciated. Just wanted to let you know about the issue.

I'd love to help, but I am not sure my current php skills are enough to refactor this, I'll look into into what happens a bit further first.
